### ISSUE TITLE
Produktanbieter - Liste / Logos, Zuordnung

### ISSUE THREAD

**Issue by ic-hv** [hypoport/tav#2]
Unser Kunde möchte neben dem Finanzierungsvorschlag auch die zugehörigen Bankdaten (Logo + Adresse) anzeigen. 

Die einzelnen Konditionen, die mir die Schnittstelle liefert, enthalten ja unter anderem das Feld "produktAnbieter". Gibt es eine Möglichkeit zu erfragen, welche konkrete Bank (Adresse + Logo) hinter dem Kürzel steckt bzw. könnten Sie mir eine Liste zukommen lassen, aus der ich die entsprechenden Zuordnungen entnehmen kann?

**Comment by ic-hv** [comment]
Der Kunde hat das nämlich hier https://module.sparkasse-bremen.de/de/home/privatkunden/kredite-und-finanzierungen/baufi_finmas_2.html entdeckt und möchte das selbst natürlich auch so haben ...

**Comment by AndreKeil** [comment]
Hallo ic-hv,

das Modul der Sparkasse Bremen ist eine individuelle Entwicklung dieses Hauses. Die Ergebnisse basieren nicht auf "Top Angebot Vertrieb (TAV)". Vielmehr nutzt die Sparkasse zur Ergebnisanzeige die "Finanzierungsvorschläge (Ergebnisliste) API" (https://github.com/hypoport/finanzierungsvorschlaege-api). Ggf. ist diese API die bessere für das Anliegen Ihres Kunden?!

Eine Erweiterung von TAV um Adresse und Logo von Produktanbietern ist aktuell nicht geplant. Ziel von TAV ist es gerade, dem Nutzer (nur) das beste im Portfolio des Website-Betreibers vorhandene Angebot zu unterbreiten - ohne gleich den dahinter stehenden Produktanbieter offenzulegen. Insofern halten wir auch keine Liste mit diesen Daten vor.

Es grüßt Sie


André Keil
